name: Foolish Kings
favicon: null
layout_spectrum: 0.25154
typography_spectrum: 0.52813
title: Foolish Kings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d9d9d9'
    - '#292929'
    - '#5e5e5e'
    - '#949494'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
