name: Foolish Kings
favicon: null
layout_spectrum: 0.74539
typography_spectrum: 0.52813
title: Foolish Kings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d9d9d9'
    - '#292929'
    - '#5e5e5e'
    - '#949494'
  brandStrength: 0.37984759197570384
  lightness: 0.5990252578631043
  saturation: 0.332003275398165
  rhythmicContrast: 0.1380085707642138
purpose: []
