name: Foolishkings
favicon: null
layout_spectrum: 0.6840653945691884
typography_spectrum: 0.4989018836058676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.37984759197570384
  lightness: 0.5990252578631043
  saturation: 0.332003275398165
  rhythmicContrast: 0.1380085707642138
purpose: []
